
version: "3.9"
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  wordpress:
    image: wordpress:php8.3-fpm
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', true);
        define('WP_DEBUG', ${WP_DEBUG});
        define('WP_REDIS_HOST', getenv('REDIS_HOST') ?: 'redis');
        define('WP_REDIS_PORT', getenv('REDIS_PORT') ?: 6379);
        define('MULTISITE', ${MULTISITE});
        define('SUBDOMAIN_INSTALL', ${SUBDOMAIN_INSTALL});
        define('DOMAIN_CURRENT_SITE', getenv('DOMAIN'));
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - wp_data:/var/www/html

  nginx:
    image: nginx:1.27-alpine
    depends_on: [wordpress]
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html:ro
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    networks: [proxy-tier]

  proxy:
    image: nginxproxy/nginx-proxy:1.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
    networks: [proxy-tier]

  acme:
    image: nginxproxy/acme-companion:2.4
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: ${ADMIN_EMAIL}
      # For Cloudflare DNS-01, uncomment and provide env vars in .env:
      # ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
      # DNSPLUGIN=cloudflare
      # CF_Email=${CLOUDFLARE_EMAIL}
      # CF_Token=${CLOUDFLARE_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
    networks: [proxy-tier]

volumes:
  db_data:
  wp_data:
  redis_data:
  proxy_certs:
  proxy_vhost:
  proxy_html:

networks:
  proxy-tier:
    external: false
