
name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          python3 -m pip install --user yamllint
      - name: ShellCheck
        run: |
          find . -type f -name "*.sh" -print0 | xargs -0 -I{} bash -c 'shellcheck "{}" || true'
      - name: YAML Lint
        run: |
          ~/.local/bin/yamllint . || true
