name: ✅ CI

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: azohra/shell-linter@v1
        with:
          severity: error
