name: CI

on:
  push:
    branches:
      - main  # You can change this to your main branch or any other branch you need to build on
  pull_request:
    branches:
      - main  # Ensure PRs are also built

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '16'  # Specify your Node.js version here

      - name: Install dependencies
        run: npm ci  # npm ci works with package-lock.json

      - name: Lint and build
        run: |
          # Add your linting and build commands here
          echo '✅ Lint & build checks passed!'

      - name: Run tests (optional)
        run: npm test  # If you have tests set up

