name: ✅ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shell lint
        uses: azohra/shell-linter@v1
        with:
          severity: error
