name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Jekyll site
        uses: actions/jekyll-build-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

