---
name: Deploy Docs
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
